import Head from "next/head";
import PageDescription from "@/components/PageDescription";
import ProjectItem from "@/components/projectItem";
import { getFoods } from "@/api/foods";

export default function Home({ foods }) {

  return (
    <>
      <Head>
        <title>3C comidas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <PageDescription
          title="DAILY MENU"
          subtitle="YUCATAN FOOD"
          description="Select your favorite dish or dessert, add it to the cart, and place you
          order."
        />
        {foods.map((food) => (
          <ProjectItem key={food._id} item={food} />
        ))}
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const foods = await getFoods();
  return {
    props: {
      foods,
    },
  };
}
