import Head from "next/head";
import PageDescription from "@/components/PageDescription";

export default function Home() {
  return (
    <>
      <Head>
        <title>3C comidas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <PageDescription
          title="3C-DAILY MENU"
          subtitle="YUCATAN FOOD"
          description="Select your favorite dish or dessert, add it to the cart, and place an
          order.You can either pick it up at the location or request home
          delivery."
        />
      </section>
    </>
  );
}
